[package]
name = "metadata-server"
version = "0.1.0"
authors = ["zoran <lazarevic.zoki91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
tokio = { version = "0.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
ccfs-commons = { path = "../ccfs-commons" }
chrono = "0.4.19"
dirs = "3.0.1"
snafu = "0.6.10"
bincode = "1.3.1"
futures = "0.3.9"
uuid = "0.8.1"
