## CCFS chunk-server config file

# server configuration
server_id: 6d53a85f-505b-4a1a-ae6d-f7c18761d04a
host: "0.0.0.0"
port: 5003

# path where the files will be stored
upload_path: ~/.ccfs/ccfs-uploads

# metadata server url
metadata_url: http://dev.ccfs.io

# ping job configuration
ping_interval: 5 # in seconds